version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: notes_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: userpassword
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PHP_CONTAINER_NAME}
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  jenkins:
    build:
      context: ./jenkins
    container_name: ${JENKINS_CONTAINER_NAME}
    user: root
    environment:
      JENKINS_OPTS: --prefix=/jenkins
    ports:
      - "${JENKINS_PORT1}:8080"
      - "${JENKINS_PORT2}:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - php
      - mysql

volumes:
  mysql-data:
  jenkins-data:
