version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: notes_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: userpassword
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins-container
    user: root
    environment:
      JENKINS_OPTS: --prefix=/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - php
      - mysql

volumes:
  mysql-data:
  jenkins-data:
