version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: notes_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: userpassword
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

volumes:
  mysql-data:
