version: "3"

services:
  db:
    image: mysql
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "user1"
    volumes:
      - ./schemas:/var/lib/mysql